coaching/urls.py
from django.contrib import admin
from django.urls import path,include
from datawork import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('', views.home,name="homepage"),
    path('contact/', views.contact,name="contact"),
    path('course/', views.course,name="course"),
    path('about/', views.about,name="about"),
    path('accounts/apply/', views.apply,name="apply"),
    path('accounts/register/', views.register,name="register"),
    path('mlogin/', views.mlogin,name="mlogin"),
    path('accounts/',include('django.contrib.auth.urls'),name="account"),
    path('student/',views.profile,name="student_profile"),
    path('student/add_course',views.add_course,name="add_course"),
    path('student/payments/',views.payment,name="payments"),
    path('student/course/',views.student_course,name="student_course"),
    path('student/update_profile/',views.update_profile,name="update_profile"),
    path('student/profile/',views.full_profile,name="full_profile"),
    path('student/setting/',views.setting,name="setting"),
    path('student/update_payments/<int:pay_id>', views.update_payment,name="update_payments"),
    path('admin/index', views.admin_home,name="admin_home"),
    path('admin/student', views.adminStudent,name="admin_student"),
    path('admin/payment', views.adminPayment,name="admin_payment"),
    path('admin/course', views.adminCourse,name="admin_course"),
    path('admin/approvepayment/<int:pay_id>', views.approvePayment,name="approve_payment"),
    path('admin/declinepayment/<int:pay_id>', views.declinePayment,name="decline_payment"),
    path('admin/approve/<int:s_id>', views.approvestudent,name="approve"),
    path('admin/searchstudent/', views.searchstudent,name="searchstudent"),
    path('admin/payment_view/<str:std_id>', views.studentPaymentView,name="payment_view"),
    path('admin/profile_view/<str:std_id>', views.StudentProfileView,name="profile_view"),
    path('admin/profile_edit/<int:s_id>', views.StudentProfileEdit,name="profile_student_edit"),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

datawork/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.utils import timezone

class Student(models.Model):
    DEGREE = (("BCA","BCA"),("BTECH","BTECH"),("BSc","BSc"),("MCA","MCA"),("OTHER","OTHER"))
    GENDER = (("M","Male"),("F","FEMALE"),("O","Other"))
    std_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    father_name = models.CharField(max_length=200)
    date_of_birth = models.CharField(max_length=200)
    degree = models.CharField(choices=DEGREE,max_length=200)
    address = models.TextField(max_length=200)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    photo = models.ImageField(upload_to="apply/image")
    gender = models.CharField(choices=GENDER,max_length=200)
    contact = models.IntegerField()
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    status = models.CharField(max_length=20,default='0',choices=(("0","Pending"),("1","Active"),("2","Courseless"),("3","takeout")))
    slugs = models.SlugField(max_length=200)

    def __str__(self):
        return self.first_name


class Course(models.Model):
    course_name = models.CharField(max_length=200)
    course_duration = models.CharField(max_length=200)
    course_fees = models.IntegerField()

    def __str__(self):
        return self.course_name


class StudentCourse(models.Model):
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    course_name = models.ForeignKey(Course,on_delete=models.DO_NOTHING)
    course_type = models.CharField(max_length=200,choices=(("1","COURSE"),("2","MONTHLY")))
    status = models.CharField(max_length=200,choices=(("1","ACTIVE"),("0","Closed")))
    data_of_join = models.DateField(default=timezone.now)

    def __str__(self):
        return self.course_name.course_name

class Payment(models.Model):
    pay_id = models.AutoField(primary_key=True)
    p_month = models.DateTimeField()
    p_amount = models.IntegerField()
    p_due = models.IntegerField()
    p_course = models.ForeignKey(StudentCourse,null=True,on_delete=models.DO_NOTHING)
    p_status = models.CharField(choices=(("0","Not paid"),("1","Pending"),("2","Paid")),max_length=200)
    user_id = models.ForeignKey(User,models.CASCADE)

    def __str__(self):
        return str(self.p_month)

templates/student/add_course.html
{% extends 'student/base_student.html' %}

{% block content %}
    <div class="col-lg-9">
    <div class="row">
        <div class="col-lg-4 mx-auto">
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'add_course' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_course_name">Course Name</label>
                                <select name="course_name" id="id_course_name">
                                      <option value="" selected>---------</option>
                                    {% for foo in course %}

                                            <option value="{{ foo.id }}">{{ foo.course_name }}</option>

                                    {% endfor %}

                                </select>
                            </div>
                            {% for f in addcourse %}
                                <div class="form-group">
                                {{ f.label_tag }}
                                {{ f }}
                                {{ f.errors }}
                                </div>
                            {% endfor %}

                        <input type="submit" class="btn btn-info btn-block">
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/student/base_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Code with sadiq</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    {% block link %}

    {% endblock %}
{% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-cws">
        <a href="{% url 'student_profile' %}" class="navbar-brand">CWS</a>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
        </ul>
    </nav>
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-3">
                <div class="card border-0 shadow-sm">
                    <img src="{{ user.0.photo.url }}" class="img-fluid my-5 px-2" alt="logo">
                    <div class="card-body">
                        <h1 class="text-truncate h5 text-center text-uppercase text-muted">{{ user.0.first_name }} {{ user.0.last_name }}</h1>
                    </div>
                </div>
                <div class="mt-4 shadow-sm card border-0">
                    <div class="card-body">
                        <h2 class="lead">Achievements</h2>
                        <hr class="m-0 p-0 bg-info">
                    </div>
                    <div class="card-footer p-0 m-0 mt-3">
                        <a href="{% url 'logout' %}" class="btn btn-danger btn-block">Logout</a>
                    </div>
                </div>
            </div>
            {% block content %}{% endblock %}
        </div>
    </div>
{% block footer %}{% endblock %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script>
        $(document).ready(function () {
            $(".form-group>input,select,textarea,input").addClass("form-control")
        })
    </script>

</body>
</html>

templates/student/course.html
{% extends 'student/base_student.html' %}


{% block content %}
    <div class="col-lg-9">
    <div class="col-lg-12">
        <h2 class="text-muted float-left h4">Manage Course ({{ stdcourse|length }})</h2>

    {% if course == 0 %}

    {% else %}
        <a href="{% url 'add_course' %}" class="float-right mb-2 btn btn-success">Add Course</a>
    {% endif %}
    </div>
    <table class="table">
        <tr>
            <th>#id</th>
            <th>Course</th>
            <th>Type</th>
            <th>Duration</th>
            <th>Fees</th>
            <th>DOJ</th>
            <th>action</th>
        </tr>
        {% for p in stdcourse %}
            <tr>
            <td>{{ p.id  }}</td>
            <td>{{ p.course_name }}</td>
            <td>{{p.course_type  }}</td>
            <td>{{p.course_name.course_duration  }}</td>
            <td>{{p.course_name.course_fees  }}</td>
            <td>{{p.data_of_join  }}</td>
            <td><a href="" class="btn btn-info">Deactivate</a></td>
            </tr>
        {% endfor %}
    </table>
    </div>
{% endblock %}

templates/student/index.html
{% extends 'student/base_student.html' %}
{% block content %}
    <div class="col-lg-9">
        {% if std_course < 1 %}
            <div class="alert text-white bg-info">
                <h2 class="h6">Not have any course </h2>
                <a href="{% url 'add_course' %}" class="btn btn-light float-right btn-sm mt-n4">add course</a>
            </div>
        {% endif %}
        {% if user.0.status == '3' %}
            <div class="alert py-5 text-white bg-danger text-center">
                <h2 class="h3">Your account is suspended</h2>
                <p>Please contact your study center for reactivation</p>
            </div>
        {% elif user.0.status == '0' %}
            <div class="alert py-5 bg-warning text-dark text-center">
                <h2>Wait you are in queue... </h2>
                <p>We will approve your account asap...</p>
            </div>
        {% else %}
            <div class="jumbotron bg-white shadow-sm">
                <p class="lead">Hello {{ user.0.first_name }}, <br>
                    <small>This is your Panel here you can manage your payment and add or remove your courses. your can
                        ask Question.. Join Quiz Challenges. and also track your performance. soon we will Add online
                        Examination.
                    </small>
                </p>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-lg-6">
                            <a href="{% url 'payments' %}" class="nav-link m-0 p-0 text-black">
                                <div class="card border-0 bg-white shadow-sm text-center text-uppercase text-primary">
                                    <div class="card-body">
                                        <h2 class="font-weight-bolder h4">Payments</h2>
                                        {% if due != 0 %}
                                            <small class="text-muted">Rs. {{ due }}</small>
                                        {% endif %}
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-6">
                            <a href="{% url 'student_course' %}" class="nav-link m-0 p-0 text-black">
                                <div class="card border-0 bg-white shadow-sm text-center text-uppercase text-success">
                                    <div class="card-body">
                                        <h2 class="font-weight-bolder h4">Courses</h2>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-6 mt-3">
                            <a href="{% url 'full_profile' %}" class="nav-link m-0 p-0 text-black">
                                <div class="card border-0 bg-white shadow-sm text-center text-uppercase text-warning">
                                    <div class="card-body">
                                        <h2 class="font-weight-bolder h4">Profile</h2>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-6 mt-3">
                            <a href="{% url 'student_course' %}" class="nav-link m-0 p-0 text-black">
                                <div class="card bg-white border-0  shadow-sm text-center text-uppercase text-center text-info">
                                    <div class="card-body">
                                        <h2 class="font-weight-bolder h4"><i class="material-icons">settings</i>
                                            Setting</h2>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-lg-6">
                            <a href="{% url 'payments' %}" class="nav-link m-0 p-0 text-black">
                                <div class="card border-0 bg-white shadow-sm text-center text-uppercase text-primary">
                                    <div class="card-body">
                                        <h2 class="font-weight-bolder h4">Q & A</h2>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-6">
                            <a href="{% url 'student_course' %}" class="nav-link m-0 p-0 text-black">
                                <div class="card border-0 bg-white shadow-sm text-center text-uppercase text-success">
                                    <div class="card-body">
                                        <h2 class="font-weight-bolder h4">Quiz</h2>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-6 mt-3">
                            <a href="{% url 'student_course' %}" class="nav-link m-0 p-0 text-black">
                                <div class="card border-0 bg-white shadow-sm text-center text-uppercase text-warning">
                                    <div class="card-body">
                                        <h2 class="font-weight-bolder h4">Score</h2>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-lg-6 mt-3">
                            <a href="{% url 'student_course' %}" class="nav-link m-0 p-0 text-black">
                                <div class="card bg-white border-0  shadow-sm text-center text-uppercase text-center text-info">
                                    <div class="card-body">
                                        <h2 class="font-weight-bolder h4">Notice</h2>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

    </div>
{% endblock %}

templates/student/payment.html
{% extends 'student/base_student.html' %}


{% block content %}

    <div class="col-lg-9">
     <div class="col-lg-12">
        <h2 class="text-muted float-left h4">Manage payments ({{ pay|length }})</h2>
    </div>
    <table class="table">
        <tr>
            <th>#Pay_id</th>
            <th>Month</th>
            <th>Amount</th>
            <th>Course</th>
            <th>Due</th>
            <th>Status</th>
        </tr>
        {% for p in pay %}
            <tr>
            <td>{{ p.pay_id  }}</td>
            <td>
                {{ p.p_month|date:"D, d-m-Y" }}

            </td>
            <td>{{p.p_amount  }}</td>
            <td>{{p.p_course  }}</td>
            <td>{{p.p_due  }}</td>
            <td>
                {% if p.p_status == "0" %}
                    <a href="{% url 'update_payments' p.pay_id %}" class="btn btn-primary btn-sm">Pay Now</a>
                {% else %}
                    <a href="" class="btn btn-warning small btn-sm disabled">Request Send</a>
                {% endif %}
            </td>
            </tr>
        {% endfor %}

    </table>
    </div>

{% endblock %}

templates/student/pending.html
{% extends 'student/base_student.html' %}


{% block content %}
    <div class="container">
    <h1>Your to apply first <a href="{% url 'apply' %}" class="btn btn-warning">Go to Apply</a></h1>
    </div>
{% endblock %}

templates/student/profile.html
{% extends 'student/base_student.html' %}

{% block content %}
    <div class="col-lg-9">
        <div class="card">
            <div class="card-body">
                <h2 class="float-left">Update profile</h2>
                <a href="{% url 'update_profile' %}" class="btn btn-info btn-sm float-right">Update Profile</a>
                <table class="table">
                    <tr>
                        <th>Full Name</th>
                        <td>{{ user.0.first_name }} {{ user.0.last_name }}</td>
                    </tr>
                    <tr>
                        <th>Father Name</th>
                        <td>{{ user.0.father_name }}</td>
                    </tr>
                    <tr>
                        <th>Date of Birth</th>
                        <td>{{ user.0.date_of_birth }}</td>
                    </tr>
                    <tr>
                        <th>Contact</th>
                        <td>{{ user.0.contact }}</td>
                    </tr>
                    <tr>
                        <th>email</th>
                        <td>{{ userdata.0.email }}</td>
                    </tr>
                    <tr>
                        <th>address</th>
                        <td>{{ user.0.address }},{{ user.0.city }} ({{ user.0.state }})</td>
                    </tr>
                    <tr>
                        <th>gender</th>
                        <td>{{ user.0.gender }}</td>
                    </tr>
                    <tr>
                        <th>degree</th>
                        <td>{{ user.0.degree }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/student/setting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/student/update_profile.html
{% extends 'student/base_student.html' %}


{% block content %}
    <div class="col-lg-9">
        <div class="card">
            <div class="card-body">
                <form action="{% url 'update_profile' %}" method="post">
                    {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                    <tr>
                        <th colspan="2"><input type="submit" class="btn btn-success btn-block"></th>
                    </tr>
                </table>

                </form>
            </div>
        </div>
    </div>
{% endblock %}